//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL___MVC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int Binhluan_id { get; set; }
        public string Anh { get; set; }
        public string Hoten { get; set; }
        public string Noidung { get; set; }
        public Nullable<int> Khachhang_id { get; set; }
        public Nullable<int> Sanpham_id { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
