//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL___MVC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDH
    {
        public int Ctdh_id { get; set; }
        public Nullable<int> Donhang_id { get; set; }
        public Nullable<int> Sanpham_id { get; set; }
        public string Tensanpham { get; set; }
        public string Anh { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<double> Tongtien { get; set; }
        public Nullable<decimal> Giakhuyenmai { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
