//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL___MVC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHDN
    {
        public int Macthdn_id { get; set; }
        public Nullable<int> Hoadonnhap_id { get; set; }
        public Nullable<int> Sanpham_id { get; set; }
        public Nullable<double> Dongia { get; set; }
        public Nullable<int> Soluong { get; set; }
    
        public virtual HoaDonNhap HoaDonNhap { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
