//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL___MVC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khuyenmai
    {
        public int Khuyenmai_id { get; set; }
        public string Tieude { get; set; }
        public string Mota { get; set; }
        public string Anh { get; set; }
    }
}
