//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL___MVC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public int LienHe_id { get; set; }
        public string Hoten { get; set; }
        public string Sdt { get; set; }
        public string Email { get; set; }
        public string Diachi { get; set; }
        public string Tieude { get; set; }
        public string Noidung { get; set; }
    }
}
