//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL___MVC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoreImg
    {
        public int MoreImg_id { get; set; }
        public string Anh1 { get; set; }
        public string Anh2 { get; set; }
        public string Anh3 { get; set; }
        public string Anh4 { get; set; }
        public string Anh5 { get; set; }
        public string Anh6 { get; set; }
        public Nullable<int> Sanpham_id { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
