//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL___MVC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTHDNs = new HashSet<CTHDN>();
            this.ThongSoKyThuats = new HashSet<ThongSoKyThuat>();
            this.CTDHs = new HashSet<CTDH>();
            this.BinhLuans = new HashSet<BinhLuan>();
            this.MoreImgs = new HashSet<MoreImg>();
        }
    
        public int Sanpham_id { get; set; }
        public Nullable<int> Maloai_id { get; set; }
        public string Tensanpham { get; set; }
        public string Anh { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string Mota { get; set; }
        public string Kichco { get; set; }
        public string Dophangiai { get; set; }
        public Nullable<decimal> Giakhuyenmai { get; set; }
        public Nullable<int> Viewcount { get; set; }
        public Nullable<int> ReducePrice { get; set; }
    
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDN> CTHDNs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongSoKyThuat> ThongSoKyThuats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDH> CTDHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoreImg> MoreImgs { get; set; }
    }
}
