//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL___MVC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string Tentk { get; set; }
        public string Matkhau { get; set; }
        public Nullable<int> Khachhang_id { get; set; }
        public Nullable<int> usergroup_id { get; set; }
        public string Anh { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
