//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL___MVC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongSoKyThuat
    {
        public int ThongSo_id { get; set; }
        public string Anh { get; set; }
        public Nullable<int> Sanpham_id { get; set; }
        public string Hedieuhang { get; set; }
        public string Ungdungphobien { get; set; }
        public string Congnghehinhanh { get; set; }
        public string Dieukhienbanggiongnoi { get; set; }
        public string Remotethongminh { get; set; }
        public string Kichthuoc { get; set; }
        public string Dophangiai { get; set; }
        public Nullable<System.DateTime> Namramat { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
